[tool.cibuildwheel]
before-all = "/bin/sh ciphercore-wrappers/python/prepare.sh"
skip = "*-musllinux*"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
]

build-backend = "setuptools.build_meta"
