[workspace]

members = [
    "ciphercore-utils",
    "ciphercore-base",
    "ciphercore-wrappers/python",
    "ciphercore-wrappers/pywrapper-macro",
]

default-members = [
    "ciphercore-utils",
    "ciphercore-base",
]