[package]
name = "ciphercore-base"
version = "0.1.0"
authors = ["CipherMode Labs, Inc."]
edition = "2021"

[dependencies]
ciphercore-utils = { path = "../ciphercore-utils" }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.68"
typetag = "0.1.7"
petgraph = "0.6.0"
maplit = "1.0.2"
openssl = "0.10"
rand = "0.8"
chrono = "0.4.19"
atomic_refcell = "0.1.8"
env_logger = "0.9.0"
clap = { version = "3.0.14", features = ["derive"] }
ndarray = "0.15.1"
json = "0.12.4"

[dev-dependencies]
serde_test = "1.0.130"

[features]
default = []
nightly-features = []

[[bin]]
name = "ciphercore_compile"
path = "src/bin/ciphercore_compile.rs"

[[bin]]
name = "ciphercore_inspect"
path = "src/bin/ciphercore_inspect.rs"

[[bin]]
name = "ciphercore_matrix_multiplication"
path = "src/bin/ciphercore_matrix_multiplication.rs"

[[bin]]
name = "ciphercore_minimum"
path = "src/bin/ciphercore_minimum.rs"

[[bin]]
name = "ciphercore_sorting"
path = "src/bin/ciphercore_sorting.rs"

[[bin]]
name = "ciphercore_visualize_context"
path = "src/bin/ciphercore_visualize_context.rs"
